### ISSUE TITLE
Please sync metadata.json with PuppetForge

### ISSUE THREAD

**Issue by Yumash** [puppetlabs/puppetlabs-mailalias_core#49]
metadata.json at repo:

` "version_requirement": ">= 6.0.0 < 9.0.0"`

metadata.json at PuppetForge

`"version_requirement": ">= 6.0.0 < 8.0.0"`

Please, redeploy the module. Thanks!

**Comment by elofu17** [comment]
Looks like it is updated now.
1.2.0 says "Puppet >= 6.0.0 < 9.0.0"

**Comment by joshcooper** [comment]
Yes this is fixed
